spring.datasource.url=jdbc:mysql://mysql-ds3-plannerdb-ds3.b.aivencloud.com:27648/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_bMuN6zt96w4imhUTpIr
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
